version: "3.9"
services:
  cast:
    build: .
    environment:
      - NGINX_VERSION=1.21.6
      - NGINX_RTMP_VERSION=1.2.2
      - FFMPEG_VERSION=5.0
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template
      - ./stunnel/:/etc/stunnel/
    ports:
      - "80:80"
      - "1935:1935" 
